version: 2.1
# Use a package of configuration called an orb.
#orbs:
  # Choose either one of the orbs below
  # welcome: circleci/welcome-orb@0.4.1
  #aws-cli: circleci/aws-cli@2.0.3
# Define the jobs we want to run for this project
jobs:
  # Exercise: Config and Deployment
  configure_infrastructure: 
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
              # You can get this ID in the section where you registered the SSH Key
              fingerprints: ["ca:dd:2e:dc:ab:f1:fb:d3:58:2b:b7:26:12:71:25:a6"] 
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible

      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -i CI:CD/exercise-config-and-deploymentinventory CI:CD/exercise-config-and-deploymentmain-remote.yml
# Sequential workflow
workflows:
  # Name the workflow
  configure_infra_wf:
    jobs:
      - configure_infrastructure