version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1.4
jobs:
  create-inventory-file:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: echo "[all]" > ~/inventory
      - persist_to_workspace:
          root: ~/
          paths:
            - inventory
  add-hosts-to-inventory-file:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: ~/
      - aws-cli/install
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID 
          aws-region: AWS_DEFAULT_REGION 
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      - run:
          name: "Add new IPs to inventory file"
          command: aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --filters "Name=tag:Project,Values=udacity" >> ~/inventory
      - run:
          name: "Print out file contents"
          command: cat ~/inventory

workflows:
  ansible-inventory-file:
    jobs:
      - create-inventory-file
      - add-hosts-to-inventory-file:
          requires:
            - create-inventory-file
